name: "Update the blog post's date"

on:
  workflow_dispatch:
    inputs:
      PR_NUM:
        description: "PR ID to amend. Leave empty to perform changes on the main branch."
        required: false
      post_name:
        description: "Blog post name to amend"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        if: ${{ github.event.inputs.PR_NUM != '' }}
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: `${{ github.event.inputs.PR_NUM }}`
            }
            core.info(`Getting PR #${{ github.event.inputs.PR_NUM }} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Failed to retrieve the PR info: ${err}`)
            }
      - name: Clone git repo from PR
        if: ${{ github.event.inputs.PR_NUM != '' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.ref }}
      - name: Clone git repo from main branch
        if: ${{ github.event.inputs.PR_NUM == '' }}
        uses: actions/checkout@v4
        with:
          ref: "main"
      - name: Update the date of ${{ github.event.inputs.post_name }}
        run: |
          gh pr checkout ${{ github.event.inputs.PR_NUM }}
          # readonly OLD_POST="${{ github.event.inputs.post_name }}"
          # readonly NEW_DATE="$(date '+%Y-%m-%d')"
          
          # if [ ! -f "_posts/${OLD_POST}" ]; then
          #   echo "Blog post ${OLD_POST} not found"
          #   exit 1
          # fi

          # readonly OLD_DATE=$(echo ${OLD_POST} | sed -E "s/([0-9]{4}\-[0-9]{2}\-[0-9]{2}).*/\1/")

          # echo "Replacing ${OLD_DATE} in the blog post"
          # sed -E -i "s/date:( *)${OLD_DATE}/date:\1${NEW_DATE}/"  "_posts/${OLD_POST}"

          # readonly NEW_POST="${NEW_DATE}"`echo "${OLD_POST}" | sed -E "s/[0-9]{4}\-[0-9]{2}\-[0-9]{2}//"`
          # echo "Renaming the ${OLD_POST} to ${NEW_POST}"

          # git mv _posts/${OLD_POST} _posts/${NEW_POST}
          # git config --global user.name "Wildfly.org CI"
          # git config --global user.email "wildfly-dev@lists.jboss.org"
          
          # echo "Committing changes and updating the PR" 
          # git commit -am "Update ${OLD_POST} blog date"
          # git push
